### PR TITLE
GCI

### PR DESCRIPTION
**Pull request by mdj117**

### CODE REVIEW

**Comment by Cervator** [comment]
Hey @mdj117 :-)

Some requests:

* Could you resize the sword image waaaay down to like 32x32 or 64x64? You might want to angle it diagonally too to fit it better within the image 
* You might also want to angle the earlier `IronEspeebastard.png` as well, as I suspect it'll look awkward in-game being vertical off to the one side of the image
* Maybe take out "Espee" entirely? From what I can gather it is a medieval French word for "sword" - meaning it might as well just be called "IronBastardSword" ?
* The earlier sword also appears to not actually be a bastard sword, just a typical sword? (https://openclipart.org/detail/169233/classic-medieval-sword)
* Could you try to get the game working inside IntelliJ so you can test the item inside the game? You can get your items with "give itemname" where "itemname" is the prefab file name (if you aren't already doing this)
* When running from IntelliJ you can use its Git integration which is waaaaay better than trying to upload files manually using the GitHub web UI :-)

**Comment by mdj117** [comment]
Hey @Cervator ,
I thought the image looked cool that's why I left it there,
Other than that I did run it on IntelliJ and it seemed fine,
I removed the espee from the name and resized the image to a suitable size,
I take it that you didn't get the GoT reference,
Regards

**Comment by Cervator** [comment]
Sorry, I did see the GoT reference alright, but am having to rush through so many tasks to review :-)

The swords themselves are plenty cool. Just the way they display in-game tends to favor diagonal weaponry. If you look at the existing textures you'll find most of them are diagonal, that way the player holds them sort in a more sensible way (although sometimes reversed in direction but that's a code fix) and you can get an image file that's more square. Right now you've got the sword at 18x64 so it is only 64 on one side.

The prefab also still has a fair amount of stray commas plus you've got two of them now, one not inside the "Iron" folder should be deleted. The display name is also still "Espee Bastarde" which *is* a cool name, but should probably match similar sword names and the file name itself :-)

When you run the game look for errors parsing JSON files, and in IntelliJ if you mark the `.prefab` files as JSON you should get syntax highlighting that would make the stray commas and such easier to spot (most notably the *last* element before a closing `}` should not have a comma)

Getting close though!

**Comment by Cervator** [comment]
I noticed a few other `.prefab` files elsewhere (not this PR) had been merged with broken JSON and one image was bad so I fixed a few things. The Steel katana for instance went from having no transparency (black background), having an odd size, and being held by its tip to:

terasology - j__dev_terasology_git_integrate_terasology - equipment - _mo_2016-12-15_23-58-30

Much better! At a nice clean 64x64. And here's the sort of awkward Iron Espee Bastard from your earlier PR, unedited image:

terasology - j__dev_terasology_git_integrate_terasology - equipment - _mo_2016-12-15_23-58-38

Thus the encouragement for diagonal :-)

**Pull request closed without merging**
