### PR TITLE
add weapon type spear

### PR DESCRIPTION
**Pull request by luxcodes**
@xrtariq2594

### CODE REVIEW

**Comment by skaldarnar** [comment]
Just a quick comment on this before @xrtariq2594 turns in: 
- the icons/textures you added seem to have blue background which I guess should be transparent

**Comment by xrtariq2594** [comment]
@HolixSF, as Skald said, could you remove the blue background? The image background should be transparent.

Also, the image of the IronSpear is an axe.

**Comment by Cervator** [comment]
Bump - @HolixSF are you still out there? We have a wood spear merged now, but your other entries would still be desirable, so long as we can fix the blue background :-)

**Comment by luxcodes** [comment]
@Cervator Hey sorry got super busy and forgot! I went ahead and changed the textures to transparent for the spears. @xrtariq2594 Also the IronSpear is a spear that just has an axehead! Similar to a Halbred =)

**Comment by xrtariq2594** [comment]
Thanks @HolixSF!

I see your point then. For now, we'll keep the graphic for the IronSpear that you selected. In the future, we'll move it over to the IronHalbred.

**Comment by Cervator** [comment]
> I see your *point*

Heh, heh :D 🗡 

Merged! Fixed a missing quote for the silver spear prefab and the target icon for the wood spear. Requested one of each and they look good in-game!

**Pull request merged**
