### PR TITLE
Removed Rings

### PR DESCRIPTION
**Pull request by Stefan-Mitic**
Removed the rings that conflicted with the other code. It now has the wooden spear that was added before.

### CODE REVIEW

**Comment by xrtariq2594** [comment]
Thanks! I'll take one last look at this tomorrow and then merge.

**Comment by xrtariq2594** [comment]
Alright, one last thing to do @Stefan-Mitic . Could you remove the following files:
-  assets/prefabs/Equipment/Copper/CopperRing.prefab 
- assets/textures/SilverRing.png 

Once those are moved, I will merge this PR in. Everything else looks fine.

**Comment by xrtariq2594** [comment]
Sorry if I'm being overbearing here, but I've discussed some things with @Cervator , and we've decided it's best if we start on a fresh PR and copy in only the three important files (WoodSpear.prefab, WoodSpear.png, and spearDamage.prefab). That way, we don't have a ton of very small commits or messy merge conflicts to resolve.

Usually, for things like these, it's good to have an experimental branch on your fork, ask for verification on that branch, and then copy over the changes onto a fresh branch, and use that one for a PR.

**Comment by Cervator** [comment]
Closing as obsolete, other PRs covered the content here. I think! :-)

**Pull request closed without merging**
