### PR TITLE
Added a Maul (War Hammer)

### PR DESCRIPTION
**Pull request by ElBatanony**

### CODE REVIEW

**Comment by Cervator** [comment]
Looks good! Heavy swinging mauls :D

One important question: did you draw the mauls yourself or grab them from somewhere, and in either case can you add an entry in the README indicating whichever? We try to keep track of artwork to credit artists :-)

Also, I imagine you added the files using the GitHub web UI? As you can tell that resulted in a bunch of separate commits. It is a lot easier when you have a fully functional source workspace as you can do everything in one commit and easily tweak at / move things around. That would also allow you to rebase/squash the existing commits here into a single one. Let me know if you want to try that - alternatively we can just squash it when we merge!

**Comment by xrtariq2594** [comment]
@ElBatanony As @Cervator said, once you add the stuff to the README file, we'll squash and merge then.

**Comment by ElBatanony** [comment]
I am sorry for this extremely long delay. I have been really busy today and I am having problems with my internet. I made the artwork myself :D. Once I get my internet running again, I will try to fix the commits issue using normal methods.

**Comment by ElBatanony** [comment]
I think I got it to work. I made a second pull request using a new branch. I am not sure if I have done it correctly, though.

**Comment by xrtariq2594** [comment]
Merged the 2.0 version :)

**Pull request closed without merging**
