### PR TITLE
Added WoodSpear

### PR DESCRIPTION
**Pull request by Stefan-Mitic**
Added the woodspear you had as an issue.

### CODE REVIEW

**Comment by xrtariq2594** [comment]
Hmmm @Stefan-Mitic , could you remove the blue background of the Wood Spear?

Also, reduce the attack stat to below 7 please. This is so that it'll be one tier lower than the Bronze Spear.

**Comment by xrtariq2594** [comment]
Thanks for fixing the Wood Spear.

It's preferred that the changes to rings are done on a different branch. Agsmith has already taken care of that.

**Comment by xrtariq2594** [comment]
For now @Stefan-Mitic , could you remove the Ring prefabs and associated graphics from your branch? Another contributor already fixed the rings issue.

**Comment by Cervator** [comment]
Closing as added manually by @xrtariq2594 via https://github.com/Terasology/Equipment/commit/0e18606f835c0588c7d99a907146fbe9bd4600d8 - thanks @Stefan-Mitic :-)

**Pull request closed without merging**
