### PR TITLE
Added Gold Katana & Magic Gold Necklace & Added Diamond Katana

### PR DESCRIPTION
**Pull request by Minege**
I added the Gold Katana & Gold Katana texture, with the image credit in the README.md file.
I also added my username in the module.txt file.

I also created the Magic Gold Necklace :D

For Google Code In 2016.

Thanks :) !

### CODE REVIEW

**Comment by Cervator** [comment]
Both items work well and you got both images explained in the readme, thanks! :-)

However, the page the golden katana is source from doesn't indicate the license under which it is released, meaning we can't use it (default is "all rights reserved"). Do you know if it is licensed somewhere in a way we can use it (such as public domain or CC BY 4.0) or alternatively could you find a different image that for sure is free for our usage?

**Comment by Minege** [comment]
Hi, 
Thanks !
For the katana, i will try to find a image that is free of usage and i will change this pull request.

**Comment by Minege** [comment]
Hello !
Here is it, i've changed the skin for the Gold Katana !
And, i've also added a new Diamond Katana :D !!

**Comment by Cervator** [comment]
Great, yay, extra stuff! But the diamond katana also doesn't have a license posted anywhere obvious :(

Am I just missing it? I see lots of buttons and stuff on the novaskin site but I don't see that item having any kind of license or usage details attached to it? 

It may very well be free but it needs to be explicitly stated somehow before we can use it :-)

**Comment by Minege** [comment]
Ok, here is it :) !

I've updated the Diamond Katana skin to one i've created 👍 
Thanks !

**Comment by Cervator** [comment]
Merged via rebase in https://github.com/Terasology/Equipment/commit/b82eb0aac61280149606c97cf7c20a4b6eded79b - thanks! :-)

**Pull request closed without merging**
