### PR TITLE
GCI: Adding Wooden Bo Staff

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Avalancs** [comment]
Hi @TheJYKoder !

Your Bo staff works fine, just wanted to ask whether you made the image, or downloaded it from the internet. Can you please put it in the readme file, like the others did?

I already approved your task, so please reply here.

**Comment by ghost** [comment]
I drew my Bo Staff using Paint.NET. Should I write that I used Paint.NET to create the image in the readme?

**Comment by xrtariq2594** [comment]
@TheJYKoder You only need to mention in the README that you created the image. Including what program you used is optional.

**Comment by ghost** [comment]
I left a note in the README, thanks!

**Comment by xrtariq2594** [comment]
@TheJYKoder Good! I'll merge this once the DiamondRingOfJuggernauts has an icon

**Comment by xrtariq2594** [comment]
Done! Thanks for adding the two items @TheJYKoder.

**Pull request merged**
